# Site settings
title: Annett Media
email: robert@annettmedia.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://www.annettmedia.com"
twitter_username: robertannett
github_username:  robertannett

# Build settings
markdown: kramdown
permalink: pretty
